[project]
name = "ceda-client"
version = "0.1.0"
description = "Python client for the CEDA (UK Climate Data Archive) JSON directory listings and file downloads."
readme = "README.md"
authors = [
    { name = "Mike Blackett", email = "27811528+mikeblackett@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "attrs>=26.1.0",
    "cattrs>=23.1.0",
    "requests>=2.34.2",
    "universal-pathlib>=0.3.10",
]

[dependency-groups]
dev = [
    "hypothesis>=6.168.0",
    "jupyterlab>=4.6.4",
    "pytest>=8.4.0",
    "pyright>=1.1.414",
    "pytest-mock>=3.15.1",
    "ruff>=0.16.8",
]

[build-system]
requires = ["uv_build>=0.9.29,<0.10.0"]
build-backend = "uv_build"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 79

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP", "TRY"]
extend-ignore = ["TRY301"]
